sudo: required
sevices:
  - docker

before_install:
  - docker build -t z1234z6789z/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true z1234z6789z/docker-react npm run test

language: generic
