sudo: required
sevices:
  - docker

before_install:
  - docker build -t z1234z6789z/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true z1234z6789z/docker-react npm run test

language: generic

deply:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-524766536517"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
